version: '2'
services:
  mhacks_db:
    extends:
      file: docker-compose.yml
      service: mhacks_db
  mhacks_website:
    extends:
      file: docker-compose.yml
      service: mhacks_website
    ports:
      - "8000:8000"
    volumes:
      - ..:/MHacks-Website
    links:
      - mhacks_db
